### ISSUE TITLE
Does this work with sub domains?

### ISSUE THREAD

**Issue by illuminate3** [dave-redfern/laravel-doctrine-tenancy#3]
I was wondering if your package will work with subdomains?

thanks

**Comment by dave-redfern** [comment]
If you use the multi-domain tenancy, yes. Though if all you want/need is basic sub-domains, Laravel 5.1+ actually supports sub-domain routing so you can do a form of tenancy without needing any additional modules. Details are documented at: https://laravel.com/docs/5.1/routing#route-group-sub-domain-routing

Otherwise, you would setup this module the same as for multi-domain tenancy. You'll need to have some database or at least an implementation of the DomainAwareTenantParticipantRepository (can be faked to use an array or other storage - not tested though). In theory it should work without Doctrine.

Hope that helps.

**Comment by illuminate3** [comment]
thanks!
