### ISSUE TITLE
Are Documents Out of Date

### ISSUE THREAD

**Issue by westcomputerconsultancy** [dave-redfern/laravel-doctrine-tenancy#6]
Hello,

I'm just wondering if the documents are out of date. In the instructions at http://somnambulist.tech/package/laravel-doctrine-tenancy/page/3 it advises

```
namespace App\Entity;
use Somnambulist\Doctrine\Contracts\GloballyTrackable as GloballyTrackableContract;
use Somnambulist\Doctrine\Traits\GloballyTrackable;
use Somnambulist\Tenancy\Contracts\TenantAware as TenantAwareContract;
use Somnambulist\Tenancy\Traits\TenantAware;

class Customer implements GloballyTrackableContract, TenantAwareContract
{
    use GloballyTrackable;
    use TenantAware;
}
```
but there is no trait GloballyTrackable that I can find. Are the up-to-date documents somewhere?

Thanks,

Stephen

**Comment by westcomputerconsultancy** [comment]
Please ignore this. I've worked out it's from another of your packages.

**Comment by dave-redfern** [comment]
@westcomputerconsultancy Hi! The docs on my main site are almost certainly out-of-date. They were originally generated automatically from the readme.md files in each project and I've not kept them up-to-date. I really need to address that - especially as I deprecated and archived many of the early domain related packages in favour of non-Laravel specific versions.

Couple of things that really need updating: I've removed most of the Doctrine event listeners in updated packages because the entities should always be "valid" and having a process modify them outside of the scope of the domain layer is bad for data integrity. Likewise, when I am building entities, I never expose get/set methods and the later packages reflect this.

The tenancy package should (in theory) be able to work with the later revisions; however instead of injecting the tenant data via the Doctrine listener, it should be part of the new object creation (e.g.: static named constructor that accepts the tenant information). I have been meaning to properly update this package (and add Laravel 8 support), but as always time is a factor.

If you find issues, please report them or make a PR and I'll update this project (I still use it for my own site so I do need to ensure it functions!).

**Comment by westcomputerconsultancy** [comment]
Ok. Many thanks for this. I thought I was going mad to begin with.

I have lots working with the old laravel-doctrine-behaviours package
installed (though I've had to fork it and change the dependencies so it
works with Laravel 8) but  it should work with somnambulist-tech/domain
instead (obviously changing a few things around)?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dave-redfern** [comment]
In theory it should though most of the traits have been removed in favour of requiring explicit coding (since with DDD you should use domain language and not every entity needs create/update dates). The docs on the main somnambulist/domain are up-to-date with usage. I've not tried using the latest version yet but I will start updating the main lib to work with Laravel 8 while overhauling the docs. Currently the tests are failing so I think that the internals on L8 may have changed a little.

**Comment by westcomputerconsultancy** [comment]
Thanks. That makes sense. I'll attempt to do that.
